apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: "16.2.0"
  interval: 6h0m0s
  targetNamespace: traefik
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    deployment:
      kind: DaemonSet
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
    experimental:
      kubernetesGateway:
        enabled: true
    metrics:
      prometheus:
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: true
        entryPoint: metrics
    service:
      externalTrafficPolicy: Local
      annotations:
        helm.sh/resource-policy: keep
    ports:
      metrics:
        expose: true
      web:
        redirectTo: websecure