---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgA3So2bXf/iPbdDmVBfhaK8FZM6F3D0k4OHbCiClmVMwGvYKKD6o/P0SwIR+kGgmhJ6nEBkaCIaRAY82sUOfl2ECFVLW/mbeXvuiQNanwajZhPdcsnyJJCpDzgCskQVIfeVcgP3bT00OEikm0e9WtduzPfogUMeiSGx77yFGbB1Z9OC/qr4IjCEO6SUlq0Z8n5WbAhrVfUa65jjsbqi+l3cwExYSizbijc9O9u22XyrYS9xBpxnAs/qjirtCICHUcLvBAFEs6/WB6OL1SoV5UbplD1vCiW1Rx6htbVgcnyzoludPLdbdRXWNguB15r3Im6xEU+jeBZn4sl95BH5Iw7WwAMNl5LXR+qB3fI3BYyrBwCKywQInAmVNy7Zv3rclO/CO5rna8a6fVhE/EoWfC8cNHIMKwjIwg54d8Bi15rIQwU/RVb6CVWmvOHA4gBFde2+2wBMvf76d44ZtJNFklWPVDyy53/dxC5GSd678fPfAAEAwbeC5OjAmfTd89t7APaxlEPFBwJopxkrUQsQvepulPgvqI8sdx0q9fewHvyJ8AF2h15Mnzk9o6F1Nw1ICWmzDNDgXUP3qk/xchqD7CUQnYhN16Sc+/pPLK4HPf7xUfCmKgBQCPJaVIesXGZqORBnccGhMxQBJXVf4P9XvYIOdUD4y/y1iACXGrqrFM2usRBAAGMsCO+OcRPg1Livwz33+tGECLJka8Xu73CfqYZ8WPXnvURqRdk2O709/t060mGtbjY6ZEWaUDnzdF7cwvArmMZuOLtTC7f4wGVe/pb51Ax+eEQgKXH+ivmhtf0o48gk9wr5phjVe58rPeWBRenp04jKiD25rOTyGR9fnuYQeYMDUwooQW2ZSn1lwJQt+GgjUcyOH/S9CFXhkeF2Fg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
