---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dk-registry
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgC1yohlhhytxL0sOKT4BMWHhVulRSpToECHmohCSTYQsgs58upFdyfWJVoRkKaci4U28jW1YOBFwNdNEBa7/1hP9Rha6Mjgl79+8Wvw2810HZx5g51LFKMgtbxuXL8v+yo1sNw4GnZhJi1U9EZDmXl248udEpV702MmERIcfHvApt7glcE6QPPVxSKy/8tSBHVxRGXvD5E3B224v05PKgYCH2gSDXq7f2W5IUDSBTbZQdasPeoPVcoXI4sBGdHbUP6imW8iGIpH1vY7dteZfq8LMl6oNlyg2KDWlmJgU8R23p+0TB0E+Wz3Wts8dC1IJch5SGof+/Yio10hWtxMj51zlUoTBdEV3gLYVYwdPGCz697se7RPj0EjFp7q5I/4MGtqu6CqBgysIWiQHhTkvgLUYVcJl4gqF0PWBE4S0CXYsN4ZbyH92zg5CYzUY91eaF0F9Wp87vu0E7pSgq5LgtOjEViw5n3ufGKNautu2u/0dJ8m5RcIqj2ZT4me/i+J2FMs1oIVrAT5gxaELcArKvuR1jGFTCmh3sLV4Up88RSVKBLB342SiGtFDiK90CEkTgaHDArQnvCU6oMfVulLxVb+mob+74TcUo/PENaSG3ZgZL6iZYqQ49AZ8BlkXXKbSLRvy7bgAhcL8hG9KrwWmRyeu/I4zD4fxDYEuYbVfNp/KtSK6OyXqe1I2qG1E4f6MLLI1p+4wIep58iLIOB/WR6L9Tsrc6MhCD9B0L5BvB0hx8/SK3yRkJlzlHZAgBdZAcBp0os+PcrqyzybUQrUOq1RaEHZT/rfn4uKxeYI9/FaZFHPhiNXIURGXNOHvOZkgy3GwsZNat6D5Yd1FxukPb7aZJ6N6Ft6X1rBLWfAJxAnvQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dk-registry
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
