apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAvNhSr+PAQKojf/93dKduN14H203q7hO+CGIMaLtBkH/m/ayg/UeMvypj7x3qCGLohIt2Se4cFGwi3g1PkVCUYdvW80jUqQQV722oCVZrUXAsHUI1NhyeCv8AQ/XsoTs97JLubcDZUJFSptrSvkuK6KEaC/6zQquAFSRkGMeva19MY2d6niKDLdvsSCwshjy9m5kKjNai7E9jl9Jq6clNjTljpPAPyPH25TD7Oqp6TbHmiAHUgBfNse0tGbXovXJrKSDvoK1TQEuwN53Gs57t/6GxOQvrBKpFb7j72QufdqqIuisPj64oemE1MnQEYBz3cNCDdKE02eDjtk2cVO8rEzy+w4La6rwsKfQb0ToSn+jlhHNjpvTVgK6F4aHmbIeHoshRh4PL5kci66/dq066kTjYAHHu1wtJ6QQfJzFkDPyt1fCNiFsFHDzlnLkCihgCNXuUznK06gR9oSek8amZeoxhPkbN1zjVBfQZGP5OLtFjYdWgkp1s6vrg5nlJYWuCvmTZ/yM7zVZXarkDtxLQCYjm6VweYORiaYcIiGdY+8jf9raOIQo43JSu1vIpyRvm4uqBdbdLTbFSvLgKY37Y15HtBZ27zeVMBHo5a6cBDi2xGBAZ0ady3d0hwXgBPs3XhKsofzyW8kT1tiexwxKPkfLnkk0YsShyOWmR26DdQ539o0MQJexytzajdV582Pbap+dnHrU6qdCjOoKvw2sFpE3LOWI18rzmo7IX1R6RSl/gRc4Q8BU6DsocNmWmZ65RWOxjhElnRoUENQFFWVMynagJmOSJ2x9beJS/mizDPrhteCSiC+2d8nWXUTW2p3uO5CcaWi6T0YTiRfgOe6ZDnGvrv7veDkNofMecOawBi1affXjYSUEzrZQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson