---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: dk-registry
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgDDF/972KIKsKZjx+ru5hh1qcn3tEa9sBLbwzwIDtD9L5SXVI4SVlRI6M067mFV1i5LvmniAUChuPVn/2pOzbW5N6mBnEVkTAtlTX6yR9oOaFzOjPcXEkTzlBGtgCkeq3hBtO68eGUxySOAF4p8p4zOAUYSZoQaCR7p3laXogz6HBYXWqVrze1QtoKYLmvjG7hZa7kGZ+dZePv81M+srFWauH1nbYIMgSowDBTjE5M470S10kbihM6z+qNhqxrVmOv0NbVuipGI0gougZZ9iByl56CCrBRzvDrE2b521mnJgbiDKpLvsepfuuRyfasSeRS+Tdzmu2/Oozlv6M2KZalz1kYSB1Ni1oJW5UpozPjZjd1G+67pcIo107zFuOZ4srGWSk7GPlbb69sfJ0dvgqtWsuBanC2CwbZ7UFO/xnRxzcpAd9UaMo5NZmRiOR/W96lzYT0NdIhkXVbu/1c7oyvM3I3Td1BKl7jwgWlBsmLgm1xvYJrWdD1fjSJJbWsxhCiJLp5BrNkhilJP5+WuUWC1IEx2LJJcFZaG+GpEX0LpYcukdtJuMy7xdUirIkTO4+xssYYK7ow4jNI7BEIw3O3K1etz2MPlJRQU/dJgRj9GdPhDfvLPkNLy0r8SIbAtlNN6bbSe6LI1mzXj26sKdDpD3PbxnzdqWeVSG6K7k67RshfTIzcmpaKSeieh6vPo9vTweeCfGlFvepU36kaP32/e5ligHKvabIiYVQQFSO0A/t/kEgTF161XoY9iQOaWxN3yElskENzPoCWxtvIqNoSBMHeJpAUutlsAF5d5iiJu/nPlUwc99NXgmUJFF9+/KNq5VlqjzyzvA1nFwtgUPYqPt6qSvHWwtFc063nSzoOIrA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: dk-registry
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
