apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - ../../../infrastructure/image-secret
configMapGenerator:
- name: common-configs
  envs:
    - config.properties
  options:
    disableNameSuffixHash: true
